default_config:

logger:
  default: info
  logs:
    custom_components.sat: debug

template:
  sensor:
    - unit_of_measurement: °C
      name: Current Temperature
      device_class: 'temperature'
      state: "{{ states('input_number.current_temperature_raw') }}"
    - unit_of_measurement: °C
      name: Outside Temperature
      device_class: 'temperature'
      state: "{{ states('input_number.outside_temperature_raw') }}"

input_number:
  current_temperature_raw:
    name: Current Temperature
    initial: 18
    min: 0
    max: 35
    step: 0.01
  outside_temperature_raw:
    name: Outside Temperature
    initial: 0
    min: 0
    max: 35
    step: 0.01

input_boolean:
  heater:
    name: Heater
    icon: mdi:heater

climate:
  - platform: generic_thermostat
    name: Heater
    heater: input_boolean.heater
    target_sensor: sensor.current_temperature