default_config:

logger:
  default: info
  logs:
    custom_components.sat: debug

homeassistant:
  customize:
    climate.heater:
      sensor_temperature_id: "sensor.heater_temperature"

template:
  sensor:
    - unit_of_measurement: °C
      name: Heater Temperature
      device_class: 'temperature'
      state: "{{ states('input_number.heater_temperature_raw') }}"
    - unit_of_measurement: °C
      name: Current Temperature
      device_class: 'temperature'
      state: "{{ states('input_number.current_temperature_raw') }}"
    - unit_of_measurement: °C
      name: Outside Temperature
      device_class: 'temperature'
      state: "{{ states('input_number.outside_temperature_raw') }}"

input_number:
  heater_temperature_raw:
    name: Heater Temperature
    initial: 19.5
    min: 0
    max: 35
    step: 0.01
  current_temperature_raw:
    name: Current Temperature
    initial: 19.5
    min: 0
    max: 35
    step: 0.01
  outside_temperature_raw:
    name: Outside Temperature
    initial: 10
    min: 0
    max: 35
    step: 0.01

input_boolean:
  heater:
    name: Heater
    icon: mdi:heater

switch:
  - platform: template
    switches:
      heater:
        value_template: "{{ is_state('input_boolean.heater', 'on') }}"
        turn_on:
          service: input_boolean.turn_on
          target:
            entity_id: input_boolean.heater
        turn_off:
          service: input_boolean.turn_off
          target:
            entity_id: input_boolean.heater

climate:
  - platform: generic_thermostat
    name: Heater
    unique_id: heater
    heater: input_boolean.heater
    target_sensor: sensor.heater_temperature