default_config:

logger:
  default: info
  logs:
    custom_components.sat: debug

homeassistant:
  customize:
    climate.heater:
      sensor_temperature_id: "sensor.heater_temperature"

climate:
  - platform: generic_thermostat
    name: Fake Thermostat
    heater: input_boolean.fake_thermostat
    target_sensor: sensor.current_temperature

switch:
  - platform: template
    switches:
      heater:
        value_template: "{{ is_state('input_boolean.heater', 'on') }}"
        turn_on:
          service: input_boolean.turn_on
          target:
            entity_id: input_boolean.heater
        turn_off:
          service: input_boolean.turn_off
          target:
            entity_id: input_boolean.heater

template:
  binary_sensor:
    name: "Window"
    device_class: "window"
    state: "{{ is_state('input_boolean.window_sensor', 'on') }}"
  sensor:
    - unit_of_measurement: °C
      name: Heater Temperature
      device_class: 'temperature'
      state: "{{ states('input_number.heater_temperature_raw') }}"
    - unit_of_measurement: °C
      name: Current Temperature
      device_class: 'temperature'
      state: "{{ states('input_number.current_temperature_raw') }}"
    - unit_of_measurement: °C
      name: Outside Temperature
      device_class: 'temperature'
      state: "{{ states('input_number.outside_temperature_raw') }}"
    - unit_of_measurement: "%"
      name: Current Humidity
      device_class: 'humidity'
      state: "{{ states('input_number.humidity_raw') }}"

input_number:
  heater_temperature_raw:
    name: Heater Temperature
    initial: 19.5
    min: 0
    max: 35
    step: 0.01
  current_temperature_raw:
    name: Current Temperature
    initial: 19.5
    min: 0
    max: 35
    step: 0.01
  outside_temperature_raw:
    name: Outside Temperature
    initial: 10
    min: 0
    max: 35
    step: 0.01
  humidity_raw:
    name: Humidity
    initial: 50
    min: 0
    max: 100
    step: 0.1

input_boolean:
  heater:
    name: Heater
  window_sensor:
    name: Window Sensor
  fake_thermostat:
    name: Fake Thermostat
