version: "3.9"
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./custom_components:/config/custom_components
      - ./configuration.yaml:/config/configuration.yaml
    restart: unless-stopped
    ports:
      - "8123:8123"