reset_integral:
  target:
    entity:
      domain: climate
      integration: "sat"

pulse_width_modulation:
  target:
    entity:
      domain: climate
      integration: "sat"
  fields:
    enabled:
      required: true
      example: true