overshoot_protection:
  name: Overshoot Protection Calculation
  description: "This service calculates the value that will be used to determine the setpoint and prevent overshooting."

clear_integral:
  name: Clear Integral
  description: "This service clears the integrating part of the PID controller for the specified climate entity. This may be useful if the integral value has become too large or if the PID controller's performance has degraded."