name: Bug Report
description: Create a report to help us improve the integration.
title: "[BUG]"
labels:
  - bug

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file an issue! Please fill out the form below so we can investigate and fix your problem.
  - type: input
    id: summary
    attributes:
      label: Summary of the bug
      description: A short, descriptive title for the issue
      placeholder: e.g., "OpenTherm gateway disconnects after restart"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Detailed steps that lead to the bug.
      placeholder: |
        1. Open Home Assistant
        2. ...
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected behavior
      description: What you expected to happen.
    validations:
      required: false
  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual behavior
      description: What actually happened.
    validations:
      required: true
  - type: input
    id: homeassistant_version
    attributes:
      label: Home Assistant version
      description: The version of Home Assistant you are using.
      placeholder: e.g., 2025.2.0
    validations:
      required: true
  - type: dropdown
    id: integration_version
    attributes:
      label: Integration version
      description: Select the SAT integration release.
      options:
        - 4.2.1
        - 4.2.0
        - 4.1.2
        - 4.1.1
        - 4.1.0
        - 4.0.0
        - Other (please specify in the summary)
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: Paste any relevant log snippets (e.g., from config entries). Use triple backticks.
      render: shell
    validations:
      required: false
