from __future__ import annotations

STORAGE_VERSION = 1

# Device behavior thresholds.
BOILER_PREHEAT_DELTA = 6.0
BOILER_SETPOINT_BAND = 1.5
BOILER_OVERSHOOT_DELTA = 2.0
BOILER_DEMAND_HYSTERESIS = 0.7
BOILER_ANTI_CYCLING_MIN_OFF_SECONDS = 180.0
BOILER_GRADIENT_THRESHOLD_UP = 0.2
BOILER_GRADIENT_THRESHOLD_DOWN = -0.1
BOILER_POST_CYCLE_SETTLING_SECONDS = 60.0
BOILER_RAMP_UP_WINDOW_SECONDS = 30.0
BOILER_RAMP_UP_RATE_CELSIUS_PER_SECOND = 0.5
BOILER_MODULATION_DELTA_THRESHOLD = 3.0
BOILER_MODULATION_RELIABILITY_MIN_SAMPLES = 8
BOILER_STALL_IGNITION_OFF_RATIO = 3.0
BOILER_STALL_IGNITION_MIN_OFF_SECONDS = 600.0
